config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :pacientes do
    resources :agendamentos
  end
  
  resources :medicos do
    resources :agendamentos
  end

  resources :agendamentos do
    match '/medicos', to: "agendamentos#medicos", via: "post"
  end

  match '/by_interval', to: "agendamentos#by_interval", via: "post"
end

app/models/agendamento.rb
  class Agendamento < ActiveRecord::Base
  belongs_to :medico
  belongs_to :paciente

  validates :medico_id, :presence => true
  validates :paciente_id, :presence => true
  validates :agenda, :presence => true
  validates :agenda, :uniqueness => {:scope => [:medico_id, :paciente_id]}
  
  def self.by_doctor(search)
    where("medico_id = ?", search) 
  end

  def self.by_data(data_inicial, data_final)
    initial = data_inicial.split('/')
    final   = data_final.split('/')
    d1 = initial[2] + '-' + initial[1] + '-' + initial[0]
    d2 = final[2] + '-' + final[1] + '-' + final[0]
    where("agenda::date between ? and ?", "#{d1}", "#{d2}") 
  end
end

app/models/medico.rb
class Medico < ActiveRecord::Base
  validates :nome, presence: {message: "Nome é Obrigatório"}
  validates :crm,  presence: {message: "CRM é Obrigatório" }
  validates :crm, format: { with: /\A([A-Z]{2}+)([0-9]{6})\z/, message: "Verifique o Formato do CRM" }

  has_many :agendamentos
  def to_s
    self.nome
  end
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  validates :nome, presence: {message: "Nome é Obrigatório"}
  validates :cpf,  presence: {message: "CPF é Obrigatório" }
  validates :cpf, :uniqueness => true

  has_many :agendamentos
  def to_s
    self.nome
  end
end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  respond_to :json, :html, :js

  def index
    @agendamento = Agendamento.new
    @agendamentos = Agendamento.all
      if params[:medico_id]
      @agendamentos = Agendamento.by_doctor(params[:medico_id])
    end

    if !params[:data_inicial].blank?
      @agendamentos = Agendamento.by_data(params[:data_inicial], params[:data_final])
    end
    respond_to do |format|
      format.html
      format.json { render json: @agendamentos.to_json(include: [:medico, :paciente]) }
    end

  end

  def new
    @agendamento = Agendamento.new
  end

  def create
    @agendamento = Agendamento.new(agendamento_params)
    respond_to do |format|
      if @agendamento.save
        format.html {redirect_to agendamentos_path, success: "Agendamento Gravado"}
      else
        format.html {render new, danger: "Verifique o Formulario"}
      end
    end      
  end

  def destroy
    @agendamento = Agendamento.find(params[:id])
    @id_med = @agendamento.medico_id
    respond_to do |format|
      if @agendamento.destroy
        format.js {}
      end      
    end
  end

  private
  def agendamento_params
    params.require(:agendamento).permit(:medico_id, :paciente_id, :agenda)
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  def index
    @medicos = Medico.all
  end

  def new
    @medico = Medico.new
  end

  def create
    @medico = Medico.new(medico_params)
    if @medico.save
      flash[:success] = "Medico Cadastrado"
      redirect_to medicos_path
    else
      flash[:danger] = "Verifique o Formulário"
      render :new
    end    
  end

  def edit
    @medico = Medico.find(params[:id])
  end

  def update
    @medico = Medico.find(params[:id])
    if @medico.update_attributes(medico_params)
      flash[:success] = "Médico Atualizado"
      redirect_to medicos_path
    else
      flash[:danger] = "Erro ao Atualizar"
      render 'edit'
    end    
  end

  def destroy
    @medico = Medico.find(params[:id])
    if @medico.destroy
      flash[:success] = "Médico Excluido"
      redirect_to medicos_path
    end
  end

  private
  def medico_params
    params.require(:medico).permit(:nome, :crm)
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
	def index
		@pacientes = Paciente.all
	end

  def new
    @paciente = Paciente.new
  end

  def create
    @paciente = Paciente.new(paciente_params)
    if @paciente.save
      flash[:success] = "Paciente Cadastrado"
      redirect_to pacientes_path
    else
      flash[:danger] = "Verifique o Formulário"
      render :new
    end    
  end

  def edit
    @paciente = Paciente.find(params[:id])
  end

  def update
    @paciente = Paciente.find(params[:id])
    if @paciente.update_attributes(paciente_params)
      flash[:success] = "Paciente Atualizado"
      redirect_to pacientes_path
    else
      flash[:danger] = "Erro ao Atualizar"
      render 'edit'
    end
  end

  def destroy
    @paciente = Paciente.find(params[:id])
    if @paciente.destroy
      flash[:success] = "Paciente Excluido"
      redirect_to pacientes_path
    end
  end

  private
  def paciente_params
    params.require(:paciente).permit(:nome, :cpf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formata_cpf(value)
    return "#{value[0..2]}.#{value[3..5]}.#{value[6..8]}-#{value[9..10]}"
  end

  def flash_message
    messages = ""
    [:success, :info, :warning, :danger].each {|type|
      if flash[type]
        messages += "<div class=\"alert alert-#{type} alert-dismissable\">"
        messages += "<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>"
        messages += "<strong>#{flash[type]}</strong>"
        messages += "</div>"
      end
    }
    messages
  end
  
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/agendamentos/_agendamento.html.erb
<table class="table table-striped">
<tr>
  <td>Cód</td>
  <td>Paciente</td>
  <td>Médico</td>
  <td>Data/Hora</td>
  <td colspan='2'>Ação</td>
</tr>
<% @agendamentos.each do |agenda| %>
  <tr>
    <td><%= agenda.id %></td>
    <td><%= agenda.paciente %></td>
    <td><%= agenda.medico %></td>
    <td><%= agenda.agenda.strftime("%d/%m/%Y %H:%M") %></td>
    <td><%= link_to "Excluir", agenda, method: :delete, data: { confirm: "Tem Certeza?"} %></td>
  </tr>
<% end -%>
</table>

app/views/agendamentos/_form.html.erb
  <%= form_for @agendamento, remote: true do |f| %>
    <table class="table table-striped">
    <% if @agendamento.errors.any? %>
      <% @agendamento.errors.messages.each do |message| %>
        <div class="message"><%= message.last.last.html_safe %></div>
      <% end %>
    <% end %>
    <tr>
      <td>
        <div class="form-group">
          <%= f.label :medico_id, "Médico:"%>
          <%= f.select("medico_id", Medico.all.collect {|m| [ m.nome, m.id ] }, { include_blank: true }) %>
        </div>        
      </td>
      <td>
        <div class="form-group">
          <%= f.label :paciente_id, "Paciente:"%>
          <%= f.select("paciente_id", Paciente.all.collect {|p| [ p.nome, p.id ] }, { include_blank: true }) %>
        </div>        
      </td>
      <td>
        <div class="form-group">
          <%= f.label :agenda, "Data:" %>
          <%= f.text_field :agenda %>
        </div>        
      </td>
    </tr>
    <tr>
      <td><%= f.submit "Gravar", :class => "btn btn-default" %></td>
    </tr>
  </table>
  <% end %>

<script type="text/javascript">
  $('#agendamento_agenda').datepicker({
    format: 'yyyy-mm-dd',
    autoclose: true,
    todayHighlight: true
  });
</script>

app/views/agendamentos/destroy.js.erb
$('div#agendamentos').html("");
var table = makeHead();
var content = '';
var medico_id = <%= @id_med %>
$.getJSON('/medicos/' + medico_id + '/agendamentos.json', function(data){
  $.each(data, function(i, item){
    id_agen = data[i].id;
    nom_med = data[i].medico["nome"];
    nom_pac = data[i].paciente["nome"];
    data_ag = data[i].agenda;
    data_fm = data_ag.substring(8,10) + "/" + data_ag.substring(5,7) + "/" + data_ag.substring(0,4);
    content += "<tr id='"+id_agen+"'><td>"+ id_agen +"</td><td>" + nom_pac + "</td><td>" + nom_med + "</td><td>" + data_fm + "</td></tr>";
  });
  table += content;
  table += "</table>"
  $('div#agendamentos').append(table);
});

  function makeHead(){
    head = "";
    head += "<table class='table table-striped'>";
    head += "  <tr>";
    head += "   <td>Cód</td>";
    head += "   <td>Paciente</td>";
    head += "   <td>Médico</td>";
    head += "   <td>Data/Hora</td>";
    head += " </tr>";
    return head;
  }

app/views/agendamentos/index.html.erb
<h4>Agenda de Atendimentos</h4>

<%= link_to("Novo Agendamento", new_agendamento_path , remote: true) %>
<div id='agendamento-form'></div>
<table class="table table-striped">
  <tr>
    <td>
      <div class="form-inline">Por Médico:
        <%= form_tag(agendamentos_path, :method => "get", id: "search-form") do %>
          <%= select("medico", "medico_id", Medico.all.collect {|m| [ m.nome, m.id ] }, { include_blank: true }) %>
          <%= submit_tag "Pesquisar", {id: 'medico' } %>
        <% end %>  
      </div>      
    </td>
    <td>
      <div class="form-inline">Por Período:
        <%= form_tag(agendamentos_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :data_inicial, "", placeholder: "Data Inicial" %>
          <%= text_field_tag :data_final, "", placeholder: "Data Final" %>
          <%= submit_tag "Pesquisar", { id: 'periodo'} %>
        <% end %>  
      </div>      
    </td>
  </tr>
</table>
<div id='agendamentos'>
  <% if @agendamentos.present? %>
    <table class="table table-striped"  id='table_agenda'>
      <tr>
        <td>Cód</td>
        <td>Paciente</td>
        <td>Médico</td>
        <td>Data/Hora</td>
        <td>Ação</td>
      </tr>
      <% @agendamentos.each do |agenda| %>
        <tr class="data">
          <td><%= agenda.id %></td>
          <td><%= agenda.paciente %></td>
          <td><%= agenda.medico %></td>
          <td><%= agenda.agenda.strftime("%d/%m/%Y %H:%M") %></td>
          <td><%= link_to "Excluir", agenda, remote: true, method: :delete, data: { confirm: "Tem Certeza?"} %></td>
        </tr>
      <% end -%>
    </table>
  <% else %>
    <p>Não foi localizado nenhum agendamento para <%= params[:medico] %>.</p>
  <% end %>  
</div>  
</div>

<script type="text/javascript">
    $('#medico').click(function(event){
      $('div#agendamentos').html("");
      var table = makeHead();
      var content = '';
      var medico_id = $('select#medico_medico_id').find(':selected').val();
      $.getJSON('/medicos/' + medico_id + '/agendamentos.json', function(data){
        $.each(data, function(i, item){
          id_agen = data[i].id;
          nom_med = data[i].medico["nome"];
          nom_pac = data[i].paciente["nome"];
          data_ag = data[i].agenda;
          data_fm = data_ag.substring(8,10) + "/" + data_ag.substring(5,7) + "/" + data_ag.substring(0,4);
          content += "<tr id='"+id_agen+"'><td>"+ id_agen +"</td><td>" + nom_pac + "</td><td>" + nom_med + "</td><td>" + data_fm + "</td></tr>";
        });
        table += content;
        table += "</table>"
        $('div#agendamentos').append(table);
      });
      event.preventDefault();
    });  

    $('#periodo').click(function(event){
      $('div#agendamentos').html("");
      var table = makeHead();
      var content = '';
      var initial_date = $('input#data_inicial').val();
      var final_date   = $('input#data_final').val();
      var url = '/agendamentos';

      $.getJSON(url,{
        data_inicial: initial_date,
        data_final: final_date,
        format: "json"
      }).done(function(data){
        $.each(data, function(i, item){
          id_agen = data[i].id;
          nom_med = data[i].medico["nome"];
          nom_pac = data[i].paciente["nome"];
          data_ag = data[i].agenda;
          data_fm = data_ag.substring(8,10) + "/" + data_ag.substring(5,7) + "/" + data_ag.substring(0,4);
          content += "<tr id='"+id_agen+"'><td>"+ id_agen +"</td><td>" + nom_pac + "</td><td>" + nom_med + "</td><td>" + data_fm + "</td></tr>";          
        });
        table += content;
        table += "</table>"
        $('div#agendamentos').append(table);
      })

      event.preventDefault();
    });


    function makeHead(){
      head = "";
      head += "<table class='table table-striped' id='table_agenda'>";
      head += "  <tr>";
      head += "   <td>Cód</td>";
      head += "   <td>Paciente</td>";
      head += "   <td>Médico</td>";
      head += "   <td>Data/Hora</td>";
      head += " </tr>";
      return head;
    }

    $('a#excluir').click(function(event){
      var id = $(this).attr('value');
      $.ajax({
        url: '/agendamentos/' + id,
        type: 'DELETE',
        success: function(data){
          alert('Excluido'); 
        }
      });
      event.preventDefault();
    });

</script>

app/views/agendamentos/new.html.erb
<h4>Cadastro de Agendamentos</h4>

<%= render 'form' %>

app/views/agendamentos/new.js.erb
$('#agendamento-form').html("<%= j (render 'form') %>");
$('#agendamento-form').slideDown(350);

app/views/home/index.html.erb
<h1>Agendamento de Atendimentos</h1>
<p>@by <a href="http://www.lucianobezerra.eti.br">Luciano Bezerra</a>	</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to image_tag("medical_icon"), root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">

    <li class="nav-item active">
      <%= link_to pacientes_path, {:class => "nav_link"} do %>
         Pacientes<span class="sr-only">(current)</span>
      <% end %>
    </li>
    <li class="nav-item">
          <%= link_to medicos_path, {:class => "nav_link"} do %>
         Médicos
      <% end %>
    </li>
    <li class="nav-item">
          <%= link_to agendamentos_path, {:class => "nav_link"} do %>
         Agendamentos
         <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sismed</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= raw flash_message %>
  <%= yield %>
</div>

</body>
</html>

app/views/medicos/_form.html.erb
<%= form_for @medico do |f| %>
  <% if @medico.errors.any? %>
    <% @medico.errors.messages.each do |message| %>
      <div class="message"><%= message.last.last.html_safe %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, "Nome:"%>
    <%= f.text_field :nome, :placeholder => "Nome", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :crm, "CRM:"%>
    <%= f.text_field :crm, :placeholder => "CRM", :class => "form-control", :maxlength => 8 %>
  </div>

  <%= f.submit "Gravar", :class => "btn btn-default" %>
<% end %>

app/views/medicos/edit.html.erb
<h4>Edição de Médicos</h4>

<%= render 'form' %>

app/views/medicos/index.html.erb
<h4>Listagem de Médicos</h4>
<table class="table table-striped">
<tr>
  <td>Cód</td>
  <td>Nome</td>
  <td>Crm</td>
  <td colspan='2'>Ação</td>
</tr>
<% @medicos.each do |med| %>
  <tr>
    <td><%= med.id %></td>
    <td><%= med.nome %></td>
    <td><%= med.crm %></td>
    <td><%= link_to "Alterar", edit_medico_path(med) %></td>
    <td><%= link_to "Excluir", med, method: :delete, data: { confirm: "Tem Certeza?"} %></td>
  </tr>
<% end -%>
</table>

<%= link_to "Novo Médico", new_medico_path %>

app/views/medicos/new.html.erb
<h4>Cadastro de Médicos</h4>

<%= render 'form' %>

app/views/pacientes/_form.html.erb
<%= form_for @paciente do |f| %>
  <% if @paciente.errors.any? %>
    <% @paciente.errors.messages.each do |message| %>
      <div class="message"><%= message.last.last.html_safe %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, "Nome:"%>
    <%= f.text_field :nome, :placeholder => "Nome", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cpf, "Cpf:"%>
    <%= f.text_field :cpf, :placeholder => "Cpf", :class => "form-control", :maxlength => 11 %>
  </div>

  <%= f.submit "Gravar", :class => "btn btn-default" %>
<% end %>

app/views/pacientes/edit.html.erb
<h4>Edição de Pacientes</h4>

<%= render 'form' %>

app/views/pacientes/index.html.erb
<h4>Listagem de Pacientes</h4>
<table class="table table-striped">
<tr>
	<td>Cód</td>
	<td>Nome</td>
	<td>Cpf</td>
  <td colspan='2'>Ação</td>
</tr>
<% @pacientes.each do |pac| %>
	<tr>
		<td><%=	pac.id %></td>
		<td><%=	pac.nome %></td>
		<td><%=	formata_cpf(pac.cpf) %></td>
    <td><%= link_to "Alterar", edit_paciente_path(pac) %></td>
    <td><%= link_to "Excluir", pac, method: :delete, data: { confirm: "Tem Certeza?"} %></td>
	</tr>
<% end -%>
</table>

<%= link_to "Novo Paciente", new_paciente_path %>

app/views/pacientes/new.html.erb
<h4>Cadastro de Pacientes</h4>

<%= render 'form' %>

app/views/shared/_flash_messages.html.erb
<% if object.nil? %>
  <% unless flash.empty? %>
    <% flash.each do |type, message| %>
      <div class="ui message">
      <i class="close icon"></i>
      <p><%= message %></p>
    <% end %>
  <% end %>
<% else %>
  <% unless object.errors.empty? %>
    <div class="ui message">
    <i class="close icon"></i>
    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end  %>
    <% object.errors.each do |attr, msg| %>
      <li><%= "#{object.class.human_attribute_name(attr).capitalize} - #{msg}" %></li>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "alert alert-#{name} alert-dismissible" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <% end -%>
<% end -%>